module.exports.uris = {
  dbpedia_uri: "https://dbpedia.org/sparql",
  sameas: "http://sameas.org/",
  bbc_artists: "http://www.bbc.co.uk/music/artists/",
  dbpedia_resource: "http://dbpedia.org/resource/",
  wikidata_uri: "https://query.wikidata.org/sparql",
  wikidata_entity_uri: "https://www.wikidata.org/wiki/",
  wikimedia_uri:
    "https://commons.wikimedia.org/w/api.php?action=query&prop=imageinfo&iiprop=url&titles=File:",
  deezer_uri: "https://api.deezer.com/search/artist/",
  musixmatch_uri: "https://api.musixmatch.com/ws/1.1/",
  openrouter_uri: "https://openrouter.ai/api/v1/chat/completions",
  mood_uri: "http://127.0.0.1:8080",
  source_dir: "static/source/",
  dest_dir: "static/reduced/",
  server: "http://127.0.0.1:7757",
  mongodb: "mongodb://%u:%p@ds143614.mlab.com:43614/musiclynx-log-dev",
  static_db_dir: "static/data/",
  ab_static_db: "ab_db",
  mp_static_db: "mp_db",
  linked_static_db: "lx_db",
  graph_static_db: "graph",
  front_template_path: "static/index.template",
};
